# Generated by Django 5.2.3 on 2025-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='routines', to='entidades.exercise'),
        ),
    ]
