# Generated by Django 5.2.3 on 2025-11-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_user_client_user_coach_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='rutine',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
