# Generated by Django 5.2.3 on 2025-12-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_rutine_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_required',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo Requerido'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Video'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='entidades.musclegroup', verbose_name='Grupo Muscular'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='entidades.musclesubgroup', verbose_name='Subgrupo Muscular'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('muscle_type', models.CharField(choices=[('group', 'Grupo Muscular'), ('subgroup', 'Subgrupo Muscular')], default='subgroup', max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'muscle_type': 'group'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='entidades.muscle', verbose_name='Grupo Padre')),
            ],
            options={
                'verbose_name': 'Músculo',
                'verbose_name_plural': 'Músculos',
                'ordering': ['muscle_type', 'name'],
            },
        ),
    ]
